import React from 'react'
import ServiceTopBanner from '../../components/Services/ServiceTopBanner';
import ServiceOne from '../../components/Services/ServiceOne';
import ServiceTwo from '../../components/Services/ServiceTwo';

export const metadata = {
  title: "Journal Selection",
  description: "Generated by create next app",
};

const JournalSelection = () => {
  return (
    <>
      <ServiceTopBanner title="Find Your Ideal" spanTitle="Journal Partner" desc="We offer you professional assistance to identify the perfect publisher for your research so your paper can find the readers it rightfully deserves." bgImageClass="journal-selection-bg" />
      <ServiceOne title="Because Your Research" spanTitle="Deserves the Right Place" desc="Getting the right journal that fits your scope, audience, and aim is daunting. The fear of rejection and incompatible journals depletes your energy. But you don't have to go through it all by yourself. We link you with the publishers of the journal, which is exactly in line with your publication objective."/>
      <ServiceTwo title="What You Will Gain Through" spanTitle="Our Services"/>
    </>
  )
}

export default JournalSelection
