import { Raleway } from 'next/font/google';
import { Playfair } from 'next/font/google';
import { Outfit } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import 'remixicon/fonts/remixicon.css';
import Header from './components/Header';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({ subsets: ['latin'], weight: ['400', '500', '600', '700'], display: 'swap' });
const playfair = Playfair({ subsets: ['latin'], weight: ['400', '500', '600', '700'], display: 'swap' });
const outfit = Outfit({ subsets: ['latin'], weight: ['400', '500', '600', '700'], display: 'swap' });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.className} ${playfair.className} ${outfit.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
