import React from 'react'
import ServiceTopBanner from '../../components/Services/ServiceTopBanner';
import ServiceOne from '../../components/Services/ServiceOne';
import ServiceTwo from '../../components/Services/ServiceTwo';

export const metadata = {
  title: "Plagiarism Check",
  description: "Generated by create next app",
};

const PlagiarismCheck = () => {
  return (
    <>
      <ServiceTopBanner title="Careful Checks With" spanTitle="Clearer Words" desc="Eu a pellentesque neque at. Tortor nullam placerat eget gravida scelerisque consequat. A miurna nulla aliquet erat dolor massa volutpat viverra. a pellentes." bgImageClass="plagiarism-check-bg" />
      <ServiceOne title="Lorem ipsum dolor sit amet" spanTitle="Consectetur Rearmet partur" desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra tortor eget
                                    lacus ullamcorper.Lorem ipsum dolor sit amet consectetur. Amet parturient elementum
                                    lobortis sit mauris blandit justo consectetur accumsan. Nulla mauris ut facilisis non
                                    non sit. Id fermentum cras sapien semper dui tempor."/>
      <ServiceTwo title="Everything You Need For" spanTitle="Publication Success"/>
    </>
  )
}

export default PlagiarismCheck
