import React from 'react'
import ServiceTopBanner from '../../components/Services/ServiceTopBanner';
import ServiceOne from '../../components/Services/ServiceOne';
import ServiceTwo from '../../components/Services/ServiceTwo';

export const metadata = {
  title: "Pre Submission Review",
  description: "Generated by create next app",
};

const PreSubmissionReview = () => {
  return (
    <>
      <ServiceTopBanner title="Let’s Make It" spanTitle="Submission-Ready" desc="You’ve spent weeks, maybe months, writing your manuscript, proposal, or paper. Now make sure it shines before you hit submit with our pre-submission review services." bgImageClass="pre-submission-review-bg" />
      <ServiceOne title="Refine What" spanTitle="Matters Most" desc="Your work carries meaning. It reflects dedication, insight, and effort, the kind that deserves more than a glance before submission. That’s where we come in. Our services give your document a thoughtful check before you send it into the world, so you can present your best version with quiet confidence."/>
      <ServiceTwo title="Everything You Need For" spanTitle="Publication Success"/>
    </>
  )
}

export default PreSubmissionReview
