import Image from "next/image";
import GlobalBtn from "../../components/GlobalBtn";
import SectionSix from "../../components/SectionSix";
import Faqs from "../../components/Faqs";
import Testimonials from "../../components/Testimonials";

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

export default function AboutUs() {
  return (
    <>
      {/* top banner */}
      <section className="top-banner">
        <div className="container">
          <div className="row align-items-center">
            <div className="col-xl-8 col-lg-6 col-md-8">
              <div className="right-col">
                <h1>About <span>Us</span></h1>
                <p>Eu a pellentesque neque at. Tortor nullam placerat eget gravida scelerisque
                  consequat. A mi urna nulla aliquet erat dolor massa volutpat viverra. a pellentes.</p>
                <GlobalBtn />
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* end */}
      {/* sec three */}
      <section className="sec-three pt-5">
        <div className="container">
          <div className="row pt-5">
            <div className="col-xl-6 col-lg-6 col-md-6">
              <div className="left-col">
                <h2>Lorem ipsum dolor sit amet <span>Consectetur Rearmet</span> partur traiger</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra tortor eget lacus
                  ullamcorper.Lorem ipsum dolor sit amet consectetur. Amet parturient elementum lobortis sit
                  mauris blandit justo consectetur accumsan. Nulla mauris ut facilisis non non sit. Id
                  fermentum cras sapien semper dui tempor. </p>
                <div className="counter">
                  <Image src="/assets/images/line.png" alt="" width={6} height={102} />
                  <div className="mb-0">
                    <span>150+</span>
                    <p>Successful Projects Delivered</p>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-xl-6 col-lg-6 col-md-6">
              <div className="right-col">
                <Image src="/assets/images/img-2.png" alt="" width={636} height={529} />
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* end */}
      {/* sec four */}
      <section className="sec-four">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-xl-8 col-lg-8 col-md-8">
              <div className="section-title">
                <h3>With a 98% client <span>satisfaction,</span> Lorem ipsum dolor sit amet
                  50M+ Partut Traiger</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra tortor eget lacus
                  ullamcorper.Lorem ipsum dolor sit amet consectetur. Amet parturient elementum.</p>
              </div>
            </div>
          </div>
          <div className="row justify-content-center g-3">
            <div className="col-xl-3 col-lg-3 col-md-6">
              <div className="sec-four-box">
                <Image src="/assets/images/icon-2.png" alt="" width={60} height={60} />
                <span>150+</span>
                <p>Over 300+ clients complete high-
                  impact projects.</p>
              </div>
            </div>
            <div className="col-xl-3 col-lg-3 col-md-6">
              <div className="sec-four-box">
                <Image src="/assets/images/icon-3.png" alt="" width={60} height={60} />
                <span>98%</span>
                <p>Over 300+ clients complete high-
                  impact projects.</p>
              </div>
            </div>
            <div className="col-xl-3 col-lg-3 col-md-6">
              <div className="sec-four-box">
                <Image src="/assets/images/icon-4.png" alt="" width={60} height={60} />
                <span>50+</span>
                <p>Over 300+ clients complete high-
                  impact projects.</p>
              </div>
            </div>
            <div className="col-xl-3 col-lg-3 col-md-6">
              <div className="sec-four-box">
                <Image src="/assets/images/icon-5.png" alt="" width={60} height={60} />
                <span>10+</span>
                <p>Over 300+ clients complete high-
                  impact projects.</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* end */}

      {/* sec six */}
      <SectionSix />
      {/* end */}

      {/* faqs */}
      <Faqs />
      {/* end */}
      {/* testimonials */}
      <Testimonials />
      {/* end */}
    </>
  );
}
